### ISSUE TITLE
Truncating the Output before it has been displayed when multiple databases are passed in.

### ISSUE THREAD

**Issue by ge0metrix** [PavelPawlowski/SQL-Scripts#15]
This truncate causes the output to only ever contain the commands for the last database in the @database parameter. 

https://github.com/PavelPawlowski/SQL-Scripts/blob/00bd2a17defaef3130cd978c08a14ffe7d27637f/RightsManagement/sp_CloneRights.sql#L407

**Comment by PavelPawlowski** [comment]
Thanks for the information. It remained there by mistake during last refactoring. Now it is removed in the script.
