### ISSUE TITLE
When cloning database roles the default schema becomes the username

### ISSUE THREAD

**Issue by daveywave** [PavelPawlowski/SQL-Scripts#2]
Great script, it comes in handy for scripting granular db object permissions, however when it comes to cloning database roles a new schema gets created and assigned to the new user/group that matches the user/group name.

Is this a limitation of sp_addrolemember? I heard Microsoft has been trying to deprecate this system stored procedure for a few versions now... I'm running SQL 2012

**Comment by PavelPawlowski** [comment]
Actually don't know why I'm using the sp_addrolemember :-) Probably coming from early versions of the script from SQL 2005 times.

I will update the stored proc to generate the ALTER ROLE in case SQL is SQL 2008+

**Comment by PavelPawlowski** [comment]
Script update so it uses ALTER ROLE for SQL 2012+
